#!/usr/bin/env python3
"""Generate Vicinae script commands for Steam: one 'Play <game>' per installed game (read from the
Flatpak Steam library's appmanifest_*.acf files) plus the main Steam pages (Library, Store, Friends,
Downloads, Settings, Big Picture). Steam has no command palette of its own; this is it.
Re-run after installing/removing games (install.sh runs it; or `python3 gen-steam.py`)."""
import glob, json, os, re, stat
HERE = os.path.dirname(os.path.abspath(__file__)); OUT = os.path.join(HERE, "scripts")
LIB = os.path.expanduser("~/.var/app/com.valvesoftware.Steam/.local/share/Steam/steamapps")
STEAM = '"$HOME/.local/bin/steam-launch"'  # forwards + recovers a wedged client (see steam-launch)
SKIP = {"Proton", "Steam Linux Runtime", "Steamworks Common"}   # tools, not games
PAGES = [  # (slug, title, icon, keywords, url)
 ("library",   "Steam Library",      "🎮", ["steam","library","games","steam library"],                 "steam://open/games"),
 ("store",     "Steam Store",        "🛒", ["steam store","store","buy games","wishlist"],              "steam://store"),
 ("friends",   "Steam Friends & Chat","💬", ["steam friends","steam chat","friends list","chat"],       "steam://open/friends"),
 ("downloads", "Steam Downloads",    "⬇️", ["steam downloads","downloads","updates","download queue"], "steam://open/downloads"),
 ("settings",  "Steam Settings",     "⚙️", ["steam settings","steam preferences","steam config"],      "steam://open/settings"),
 ("bigpicture","Steam Big Picture",  "📺", ["big picture","steam tv mode","controller mode","couch"],  "steam://open/bigpicture"),
 ("screenshots","Steam Screenshots", "📸", ["steam screenshots","game screenshots"],                   "steam://open/screenshots"),
]
HEAD = ("#!/bin/bash\n# @vicinae.schemaVersion 1\n# @vicinae.title {title}\n# @vicinae.mode silent\n"
        "# @vicinae.icon {icon}\n# @vicinae.keywords {kw}\n# @vicinae.packageName Steam\n"
        "# GENERATED by gen-steam.py, do not edit by hand.\n"
        "export PATH=\"$HOME/.local/bin:/usr/local/bin:/usr/bin:/bin\"\n# Vicinae kills a silent script ~10s after launch, so never exec a GUI app: detach it.\nlaunch(){{ setsid -f \"$@\" >/dev/null 2>&1; }}\n")
def write(name, title, icon, kw, body):
    p = os.path.join(OUT, name + ".sh")
    open(p, "w").write(HEAD.format(title=title, icon=icon, kw=json.dumps(kw)) + body + "\n")
    os.chmod(p, os.stat(p).st_mode | stat.S_IXUSR | stat.S_IXGRP | stat.S_IXOTH)
for old in glob.glob(os.path.join(OUT, "steam-*.sh")):   # drop commands for uninstalled games
    os.remove(old)
games = []
for f in glob.glob(os.path.join(LIB, "appmanifest_*.acf")):
    txt = open(f, errors="ignore").read()
    appid = re.search(r'"appid"\s+"(\d+)"', txt); name = re.search(r'"name"\s+"([^"]+)"', txt)
    if not (appid and name) or any(name.group(1).startswith(s) for s in SKIP): continue
    games.append((appid.group(1), name.group(1)))
for appid, name in sorted(games, key=lambda g: g[1].lower()):
    slug = re.sub(r"[^a-z0-9]+", "-", name.lower()).strip("-")
    words = [w for w in re.split(r"[^a-z0-9]+", name.lower()) if len(w) > 2]
    write("steam-play-" + slug, f"Play {name}", "🕹️", ["play", "launch", "game", "steam", name.lower()] + words,
          f"launch {STEAM} steam://rungameid/{appid}")
for slug, title, icon, kw, url in PAGES:
    write("steam-" + slug, title, icon, kw, f"launch {STEAM} {url}")
print(f"wrote {len(games)} game + {len(PAGES)} page commands to {OUT}")
