#!/bin/bash
# @vicinae.schemaVersion 1
# @vicinae.title Power
# @vicinae.mode silent
# @vicinae.icon 🔋
# @vicinae.keywords ["power", "battery", "sleep", "suspend settings", "screen blank", "performance mode", "power mode", "idle", "settings"]
# @vicinae.packageName Settings
# GENERATED by gen-settings.py, do not edit by hand.
export PATH="$HOME/.local/bin:/usr/local/bin:/usr/bin:/bin"
exec gnome-control-center power
