#!/bin/bash
# @vicinae.schemaVersion 1
# @vicinae.title System
# @vicinae.mode silent
# @vicinae.icon ℹ️
# @vicinae.keywords ["system", "about", "about this pc", "hostname", "device name", "software updates", "secure shell", "os version", "hardware info", "settings"]
# @vicinae.packageName Settings
# GENERATED by gen-settings.py, do not edit by hand.
export PATH="$HOME/.local/bin:/usr/local/bin:/usr/bin:/bin"
exec gnome-control-center system
