#!/bin/bash
# @vicinae.schemaVersion 1
# @vicinae.title Wi-Fi
# @vicinae.mode silent
# @vicinae.icon 📶
# @vicinae.keywords ["wifi", "wi-fi", "wireless", "wlan", "hotspot", "networks", "ssid", "settings"]
# @vicinae.packageName Settings
# GENERATED by gen-settings.py, do not edit by hand.
export PATH="$HOME/.local/bin:/usr/local/bin:/usr/bin:/bin"
exec gnome-control-center wifi
