#!/bin/bash
# @vicinae.schemaVersion 1
# @vicinae.title Keyboard
# @vicinae.mode silent
# @vicinae.icon ⌨️
# @vicinae.keywords ["keyboard", "shortcuts", "keyboard shortcuts", "input sources", "layout", "compose key", "emoji", "settings"]
# @vicinae.packageName Settings
# GENERATED by gen-settings.py, do not edit by hand.
export PATH="$HOME/.local/bin:/usr/local/bin:/usr/bin:/bin"
exec gnome-control-center keyboard
