#!/bin/bash
# @vicinae.schemaVersion 1
# @vicinae.title Search
# @vicinae.mode silent
# @vicinae.icon 🔍
# @vicinae.keywords ["search settings", "search providers", "overview search", "settings"]
# @vicinae.packageName Settings
# GENERATED by gen-settings.py, do not edit by hand.
export PATH="$HOME/.local/bin:/usr/local/bin:/usr/bin:/bin"
exec gnome-control-center search
