#!/bin/bash
# @vicinae.schemaVersion 1
# @vicinae.title Online Accounts
# @vicinae.mode silent
# @vicinae.icon ☁️
# @vicinae.keywords ["online accounts", "google account", "microsoft account", "nextcloud", "accounts", "settings"]
# @vicinae.packageName Settings
# GENERATED by gen-settings.py, do not edit by hand.
export PATH="$HOME/.local/bin:/usr/local/bin:/usr/bin:/bin"
exec gnome-control-center online-accounts
