#!/bin/bash
# @vicinae.schemaVersion 1
# @vicinae.title Accessibility
# @vicinae.mode silent
# @vicinae.icon ♿
# @vicinae.keywords ["accessibility", "universal access", "a11y", "large text", "zoom", "high contrast", "screen reader", "cursor size", "settings"]
# @vicinae.packageName Settings
# GENERATED by gen-settings.py, do not edit by hand.
export PATH="$HOME/.local/bin:/usr/local/bin:/usr/bin:/bin"
exec gnome-control-center universal-access
