#!/bin/bash
# @vicinae.schemaVersion 1
# @vicinae.title Apps
# @vicinae.mode silent
# @vicinae.icon 📦
# @vicinae.keywords ["apps", "applications", "default apps", "default browser", "file associations", "removable media", "startup", "settings"]
# @vicinae.packageName Settings
# GENERATED by gen-settings.py, do not edit by hand.
export PATH="$HOME/.local/bin:/usr/local/bin:/usr/bin:/bin"
# Vicinae kills a silent script ~10s after launch, so never exec a GUI app: detach it.
launch(){ setsid -f "$@" >/dev/null 2>&1; }
launch gnome-control-center applications
