#!/bin/bash
# @vicinae.schemaVersion 1
# @vicinae.title Multitasking
# @vicinae.mode silent
# @vicinae.icon 🗂️
# @vicinae.keywords ["multitasking", "workspaces", "hot corner", "app switching", "workspace", "settings"]
# @vicinae.packageName Settings
# GENERATED by gen-settings.py, do not edit by hand.
export PATH="$HOME/.local/bin:/usr/local/bin:/usr/bin:/bin"
exec gnome-control-center multitasking
