#!/bin/bash
# @vicinae.schemaVersion 1
# @vicinae.title Privacy & Security
# @vicinae.mode silent
# @vicinae.icon 🔒
# @vicinae.keywords ["privacy", "security", "location", "camera access", "screen lock", "file history", "diagnostics", "thunderbolt", "settings"]
# @vicinae.packageName Settings
# GENERATED by gen-settings.py, do not edit by hand.
export PATH="$HOME/.local/bin:/usr/local/bin:/usr/bin:/bin"
exec gnome-control-center privacy
