#!/bin/bash
# @vicinae.schemaVersion 1
# @vicinae.title Apps
# @vicinae.mode silent
# @vicinae.icon 📦
# @vicinae.keywords ["apps", "applications", "default apps", "default browser", "file associations", "removable media", "startup", "settings"]
# @vicinae.packageName Settings
# GENERATED by gen-settings.py, do not edit by hand.
export PATH="$HOME/.local/bin:/usr/local/bin:/usr/bin:/bin"
exec gnome-control-center applications
