#!/bin/bash
# @vicinae.schemaVersion 1
# @vicinae.title Power
# @vicinae.mode silent
# @vicinae.icon 🔋
# @vicinae.keywords ["power", "battery", "sleep", "suspend settings", "screen blank", "performance mode", "power mode", "idle", "settings"]
# @vicinae.packageName Settings
# GENERATED by gen-settings.py, do not edit by hand.
export PATH="$HOME/.local/bin:/usr/local/bin:/usr/bin:/bin"
# Vicinae kills a silent script ~10s after launch, so never exec a GUI app: detach it.
launch(){ setsid -f "$@" >/dev/null 2>&1; }
launch gnome-control-center power
