#!/bin/bash
# @vicinae.schemaVersion 1
# @vicinae.title Appearance
# @vicinae.mode silent
# @vicinae.icon 🎨
# @vicinae.keywords ["appearance", "background", "wallpaper", "theme", "dark mode", "light mode", "style", "accent color", "settings"]
# @vicinae.packageName Settings
# GENERATED by gen-settings.py, do not edit by hand.
export PATH="$HOME/.local/bin:/usr/local/bin:/usr/bin:/bin"
exec gnome-control-center background
