#!/bin/bash
# @vicinae.schemaVersion 1
# @vicinae.title Network
# @vicinae.mode silent
# @vicinae.icon 🌐
# @vicinae.keywords ["network", "ethernet", "lan", "vpn", "proxy", "ip address", "dns", "internet", "settings"]
# @vicinae.packageName Settings
# GENERATED by gen-settings.py, do not edit by hand.
export PATH="$HOME/.local/bin:/usr/local/bin:/usr/bin:/bin"
exec gnome-control-center network
