#!/bin/bash
# @vicinae.schemaVersion 1
# @vicinae.title Wellbeing
# @vicinae.mode silent
# @vicinae.icon 🧘
# @vicinae.keywords ["wellbeing", "screen time", "break reminders", "eye strain", "settings"]
# @vicinae.packageName Settings
# GENERATED by gen-settings.py, do not edit by hand.
export PATH="$HOME/.local/bin:/usr/local/bin:/usr/bin:/bin"
exec gnome-control-center wellbeing
