#!/bin/bash
# @vicinae.schemaVersion 1
# @vicinae.title Users
# @vicinae.mode silent
# @vicinae.icon 👤
# @vicinae.keywords ["users", "user", "account", "password", "fingerprint", "auto login", "avatar", "settings"]
# @vicinae.packageName Settings
# GENERATED by gen-settings.py, do not edit by hand.
export PATH="$HOME/.local/bin:/usr/local/bin:/usr/bin:/bin"
exec gnome-control-center users
