#!/bin/bash
# @vicinae.schemaVersion 1
# @vicinae.title Displays
# @vicinae.mode silent
# @vicinae.icon 🖥️
# @vicinae.keywords ["display", "displays", "monitor", "monitors", "resolution", "scaling", "scale", "refresh rate", "hdmi", "night light", "orientation", "settings"]
# @vicinae.packageName Settings
# GENERATED by gen-settings.py, do not edit by hand.
export PATH="$HOME/.local/bin:/usr/local/bin:/usr/bin:/bin"
exec gnome-control-center display
