#!/bin/bash
# @vicinae.schemaVersion 1
# @vicinae.title Notifications
# @vicinae.mode silent
# @vicinae.icon 🔔
# @vicinae.keywords ["notifications", "do not disturb", "dnd", "alerts", "banners", "lock screen notifications", "settings"]
# @vicinae.packageName Settings
# GENERATED by gen-settings.py, do not edit by hand.
export PATH="$HOME/.local/bin:/usr/local/bin:/usr/bin:/bin"
exec gnome-control-center notifications
