#!/bin/bash
# @vicinae.schemaVersion 1
# @vicinae.title Mouse & Touchpad
# @vicinae.mode silent
# @vicinae.icon 🖱️
# @vicinae.keywords ["mouse", "touchpad", "trackpad", "pointer", "scroll", "natural scrolling", "tap to click", "settings"]
# @vicinae.packageName Settings
# GENERATED by gen-settings.py, do not edit by hand.
export PATH="$HOME/.local/bin:/usr/local/bin:/usr/bin:/bin"
exec gnome-control-center mouse
