#!/bin/bash
# @vicinae.schemaVersion 1
# @vicinae.title Date & Time
# @vicinae.mode silent
# @vicinae.icon 🕒
# @vicinae.keywords ["date", "time", "clock", "timezone", "time zone", "ntp", "24 hour", "settings"]
# @vicinae.packageName Settings
# GENERATED by gen-settings.py, do not edit by hand.
export PATH="$HOME/.local/bin:/usr/local/bin:/usr/bin:/bin"
exec gnome-control-center datetime
