#!/bin/bash
# @vicinae.schemaVersion 1
# @vicinae.title Mobile Network
# @vicinae.mode silent
# @vicinae.icon 📱
# @vicinae.keywords ["wwan", "mobile network", "cellular", "sim", "lte", "settings"]
# @vicinae.packageName Settings
# GENERATED by gen-settings.py, do not edit by hand.
export PATH="$HOME/.local/bin:/usr/local/bin:/usr/bin:/bin"
exec gnome-control-center wwan
