#!/bin/bash
# @vicinae.schemaVersion 1
# @vicinae.title Play Hades II
# @vicinae.mode silent
# @vicinae.icon 🕹️
# @vicinae.keywords ["play", "launch", "game", "steam", "hades ii", "hades"]
# @vicinae.packageName Steam
# GENERATED by gen-steam.py, do not edit by hand.
export PATH="$HOME/.local/bin:/usr/local/bin:/usr/bin:/bin"
# Vicinae kills a silent script ~10s after launch, so never exec a GUI app: detach it.
launch(){ setsid -f "$@" >/dev/null 2>&1; }
launch "$HOME/.local/bin/steam-launch" steam://rungameid/1145350
