#!/bin/bash
# @vicinae.schemaVersion 1
# @vicinae.title Play Cyberpunk 2077
# @vicinae.mode silent
# @vicinae.icon 🕹️
# @vicinae.keywords ["play", "launch", "game", "steam", "cyberpunk 2077", "cyberpunk", "2077"]
# @vicinae.packageName Steam
# GENERATED by gen-steam.py, do not edit by hand.
export PATH="$HOME/.local/bin:/usr/local/bin:/usr/bin:/bin"
# Vicinae kills a silent script ~10s after launch, so never exec a GUI app: detach it.
launch(){ setsid -f "$@" >/dev/null 2>&1; }
launch flatpak run com.valvesoftware.Steam steam://rungameid/1091500
