#!/bin/bash
# @vicinae.schemaVersion 1
# @vicinae.title Steam Settings
# @vicinae.mode silent
# @vicinae.icon ⚙️
# @vicinae.keywords ["steam settings", "steam preferences", "steam config"]
# @vicinae.packageName Steam
# GENERATED by gen-steam.py, do not edit by hand.
export PATH="$HOME/.local/bin:/usr/local/bin:/usr/bin:/bin"
# Vicinae kills a silent script ~10s after launch, so never exec a GUI app: detach it.
launch(){ setsid -f "$@" >/dev/null 2>&1; }
launch flatpak run com.valvesoftware.Steam steam://open/settings
