#!/bin/bash
# @vicinae.schemaVersion 1
# @vicinae.title Bluetooth Off
# @vicinae.mode silent
# @vicinae.icon 🔴
# @vicinae.keywords ["bluetooth off", "disable bluetooth", "turn off bluetooth", "bt off"]
# @vicinae.packageName System
# GENERATED by gen-settings.py, do not edit by hand.
export PATH="$HOME/.local/bin:/usr/local/bin:/usr/bin:/bin"
# Vicinae kills a silent script ~10s after launch, so never exec a GUI app: detach it.
launch(){ setsid -f "$@" >/dev/null 2>&1; }
rfkill block bluetooth && notify-send 'Bluetooth' 'Radio blocked'
