#!/bin/bash
# @vicinae.schemaVersion 1
# @vicinae.title Restart
# @vicinae.mode silent
# @vicinae.icon 🔁
# @vicinae.keywords ["restart", "reboot"]
# @vicinae.packageName System
# GENERATED by gen-settings.py, do not edit by hand.
export PATH="$HOME/.local/bin:/usr/local/bin:/usr/bin:/bin"
exec gnome-session-quit --reboot
