#!/bin/bash
# @vicinae.schemaVersion 1
# @vicinae.title All Settings
# @vicinae.mode silent
# @vicinae.icon ⚙️
# @vicinae.keywords ["settings", "system settings", "preferences", "control center", "gnome settings"]
# @vicinae.packageName System
# GENERATED by gen-settings.py, do not edit by hand.
export PATH="$HOME/.local/bin:/usr/local/bin:/usr/bin:/bin"
exec gnome-control-center
