#!/bin/bash
# @vicinae.schemaVersion 1
# @vicinae.title Wi-Fi Networks (list)
# @vicinae.mode fullOutput
# @vicinae.icon 📋
# @vicinae.keywords ["wifi list", "wifi networks", "available networks", "scan wifi"]
# @vicinae.packageName System
# GENERATED by gen-settings.py, do not edit by hand.
export PATH="$HOME/.local/bin:/usr/local/bin:/usr/bin:/bin"
# Vicinae kills a silent script ~10s after launch, so never exec a GUI app: detach it.
launch(){ setsid -f "$@" >/dev/null 2>&1; }
nmcli -f SSID,SIGNAL,SECURITY dev wifi list 2>&1 | head -25
