#!/bin/bash
# @vicinae.schemaVersion 1
# @vicinae.title Suspend
# @vicinae.mode silent
# @vicinae.icon 🌙
# @vicinae.keywords ["suspend", "sleep", "standby"]
# @vicinae.packageName System
# GENERATED by gen-settings.py, do not edit by hand.
export PATH="$HOME/.local/bin:/usr/local/bin:/usr/bin:/bin"
exec systemctl suspend
