#!/bin/bash
# @vicinae.schemaVersion 1
# @vicinae.title Bluetooth Devices (list)
# @vicinae.mode fullOutput
# @vicinae.icon 📋
# @vicinae.keywords ["bluetooth devices", "paired devices", "connected devices", "bt list"]
# @vicinae.packageName System
# GENERATED by gen-settings.py, do not edit by hand.
export PATH="$HOME/.local/bin:/usr/local/bin:/usr/bin:/bin"
# Vicinae kills a silent script ~10s after launch, so never exec a GUI app: detach it.
launch(){ setsid -f "$@" >/dev/null 2>&1; }
bluetoothctl devices 2>/dev/null | sed 's/^Device //' | sort > /tmp/bt-devices.txt; [ -s /tmp/bt-devices.txt ] || echo 'No Bluetooth adapter / no paired devices' > /tmp/bt-devices.txt; cat /tmp/bt-devices.txt
