#!/bin/bash
# @vicinae.schemaVersion 1
# @vicinae.title Wi-Fi Off
# @vicinae.mode silent
# @vicinae.icon 🔴
# @vicinae.keywords ["wifi off", "disable wifi", "turn off wifi", "wireless off"]
# @vicinae.packageName System
# GENERATED by gen-settings.py, do not edit by hand.
export PATH="$HOME/.local/bin:/usr/local/bin:/usr/bin:/bin"
# Vicinae kills a silent script ~10s after launch, so never exec a GUI app: detach it.
launch(){ setsid -f "$@" >/dev/null 2>&1; }
nmcli radio wifi off && notify-send 'Wi-Fi' 'Radio off'
