#!/bin/bash
# @vicinae.schemaVersion 1
# @vicinae.title Shut Down
# @vicinae.mode silent
# @vicinae.icon ⏻
# @vicinae.keywords ["shut down", "shutdown", "power off", "turn off"]
# @vicinae.packageName System
# GENERATED by gen-settings.py, do not edit by hand.
export PATH="$HOME/.local/bin:/usr/local/bin:/usr/bin:/bin"
exec gnome-session-quit --power-off
