#!/bin/bash
# @vicinae.schemaVersion 1
# @vicinae.title Airplane Mode (toggle)
# @vicinae.mode silent
# @vicinae.icon ✈️
# @vicinae.keywords ["airplane", "airplane mode", "flight mode", "all radios"]
# @vicinae.packageName System
# GENERATED by gen-settings.py, do not edit by hand.
export PATH="$HOME/.local/bin:/usr/local/bin:/usr/bin:/bin"
if rfkill list | grep -q 'Soft blocked: yes'; then rfkill unblock all; notify-send 'Airplane mode' 'Off'; else rfkill block all; notify-send 'Airplane mode' 'On'; fi
