#!/bin/bash
# @vicinae.schemaVersion 1
# @vicinae.title Wi-Fi On
# @vicinae.mode silent
# @vicinae.icon 🟢
# @vicinae.keywords ["wifi on", "enable wifi", "turn on wifi", "wireless on"]
# @vicinae.packageName System
# GENERATED by gen-settings.py, do not edit by hand.
export PATH="$HOME/.local/bin:/usr/local/bin:/usr/bin:/bin"
nmcli radio wifi on && notify-send 'Wi-Fi' 'Radio on'
