#!/bin/bash
# @vicinae.schemaVersion 1
# @vicinae.title Bluetooth Off
# @vicinae.mode silent
# @vicinae.icon 🔴
# @vicinae.keywords ["bluetooth off", "disable bluetooth", "turn off bluetooth", "bt off"]
# @vicinae.packageName System
# GENERATED by gen-settings.py, do not edit by hand.
export PATH="$HOME/.local/bin:/usr/local/bin:/usr/bin:/bin"
rfkill block bluetooth && notify-send 'Bluetooth' 'Radio blocked'
