#!/bin/bash
# @vicinae.schemaVersion 1
# @vicinae.title Bluetooth On
# @vicinae.mode silent
# @vicinae.icon 🟢
# @vicinae.keywords ["bluetooth on", "enable bluetooth", "turn on bluetooth", "bt on"]
# @vicinae.packageName System
# GENERATED by gen-settings.py, do not edit by hand.
export PATH="$HOME/.local/bin:/usr/local/bin:/usr/bin:/bin"
rfkill unblock bluetooth && notify-send 'Bluetooth' 'Radio unblocked'
