#!/bin/bash
# @vicinae.schemaVersion 1
# @vicinae.title Log Out
# @vicinae.mode silent
# @vicinae.icon 🚪
# @vicinae.keywords ["log out", "logout", "sign out", "end session"]
# @vicinae.packageName System
# GENERATED by gen-settings.py, do not edit by hand.
export PATH="$HOME/.local/bin:/usr/local/bin:/usr/bin:/bin"
exec gnome-session-quit --logout
