#!/bin/bash
# @vicinae.schemaVersion 1
# @vicinae.title Extensions
# @vicinae.mode silent
# @vicinae.icon 🧩
# @vicinae.keywords ["extensions", "gnome extensions", "extension manager", "shell extensions"]
# @vicinae.packageName System
# GENERATED by gen-settings.py, do not edit by hand.
export PATH="$HOME/.local/bin:/usr/local/bin:/usr/bin:/bin"
exec gnome-extensions-app
