[Appearance]
style=kvantum-dark
icon_theme=Adwaita
standard_dialogs=xdgdesktopportal

[Fonts]
fixed="Adwaita Mono,11,-1,5,400,0,0,0,0,0,0,0,0,0,0,1"
general="Adwaita Sans,11,-1,5,400,0,0,0,0,0,0,0,0,0,0,1"
